# LVA Audio  PulseAudio client config
# Used by pactl and any client inside this container

default-server = unix:/run/lva/audio/pulse/native
autospawn = no
daemon-binary = /bin/true
enable-shm = false